### ISSUE TITLE
Provide an option for rendering custom component

### ISSUE THREAD

**Issue by talatkuyuk** [koka831/remark-custom-container#138]
**Could you provide an optional option for rendering custom component.**

```ts
use(container, {
  className: string, // default to "remark-container",
  containerTag: string // default to "div"
  render?: (type:string, title: string) => JSX.Element,    // <----- something like that (actually type corresponds with the className I suppose)
})
```

The below component (currently in the package) could be the default if any render function does not provided, of course.
```jsx
<div class="remark-container className">
  <div class="remark-container__title">
    Custom Title
  </div>
  Container Body
</div>
```

**Wanted feature:**  define a custom render function in the options in order to render the custom component like attachment as an example.

```jsx
render?: (type:string, title: string) => <Callout type={type} title={title}>{children}</Callout>
```

The **type** could be `'warning' | "caution" | 'danger' | 'info' | 'note' | 'tip'`  etc.

I mean this package could be more dynamic in the next versions. Thank you for initiating this project.

![Görüntü 22 11 2022 ÖS 4 51](https://user-images.githubusercontent.com/30029208/203330951-31aed444-d676-4951-b37a-bc12bafd371f.jpeg)

**Comment by koka831** [comment]
Hi @talatkuyuk, thank you for reporting the issue!

Looks interesting. However, I think we need to consider that this plugin is a one of a transform plugin, so it might not be better to convert given AST into JSX notation immediately.
If we provide an option like that, it may be like https://github.com/Nevenall/remark-containers#options?

**Comment by talatkuyuk** [comment]
Okey, agree. I am going to close the issue; but will create another one about extracting the title.
