### ISSUE TITLE
1.3.0 does not seem to be updated accordingly

### ISSUE THREAD

**Issue by talatkuyuk** [koka831/remark-custom-container#154]
When I install the package as latest version (1.3.0) **from npm**, _I see the ReadMe file is updated_; but I see the **only two index.js files** in the directories `node_modules/remark-custom-container/dist` and `node_modules/remark-custom-container/dist/esm` which seem not to updated according to latest changes.

![Görüntü 10 12 2022 ÖS 6 52](https://user-images.githubusercontent.com/30029208/206863694-46577be6-b427-4d63-82d4-facdd9c031a1.jpeg)

**Comment by koka831** [comment]
Thanks for reporting, it doesn't include latest dist. 
It'll fixed in https://github.com/koka831/remark-custom-container/pull/155 and I'll release it in 1.3.1.

**Comment by koka831** [comment]
@talatkuyuk Could you try https://www.npmjs.com/package/remark-custom-container/v/1.3.1 ?

**Comment by talatkuyuk** [comment]
Done. It seems to be updated now, thanks for quick action 👍
